apiVersion: v1
kind: Service
metadata:
  name: pic2video-morph-service
  labels:
    app: pic2video-morph-service
spec:
  type: LoadBalancer
  selector:
    app: pic2video-morph-service
  ports:
    - name: http
      port: 80
      targetPort: 8080

